name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      EXPO_NO_TELEMETRY: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Print versions
        run: |
          echo "Node: $(node -v)"
          echo "npm:  $(npm -v)"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund --legacy-peer-deps
          fi

      - name: Expo CLI check
        run: npx --yes expo --version

      - name: Type check
        run: |
          if npm run | grep -q "typecheck"; then
            npm run typecheck
          else
            npx tsc -p tsconfig.json --noEmit
          fi

      - name: Lint
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            npx eslint . --ext .ts,.tsx
          fi

      - name: Prettier check
        run: |
          if npm run | grep -q "format:check"; then
            if [ -f node_modules/.bin/prettier ]; then
              echo "Using local Prettier (script)"
              npm run format:check
            else
              echo "Local Prettier not found → using npx fallback"
              npx --yes prettier --check .
            fi
          else
            echo "No format:check script; skipping."
          fi

