name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Enable Corepack (for Yarn/PNPM if present)
        run: corepack enable

      - name: Install dependencies (npm or yarn; lockfile or not)
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: "true"
        run: |
          echo "Node: $(node -v)"
          echo "NPM:  $(npm -v)"
          if [ -f yarn.lock ]; then
            echo "Detected yarn.lock → using Yarn"
            yarn --version
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            echo "Detected package-lock.json → using npm ci"
            npm ci --no-audit --no-fund --prefer-offline
          else
            echo "No lockfile → using npm install (RN-friendly flags)"
            npm install --no-audit --no-fund --legacy-peer-deps
          fi

      - name: Type check (prefer script; fallback to npx)
        run: |
          if npm run | grep -q "typecheck"; then
            npm run typecheck
          else
            npx tsc -p tsconfig.json --noEmit
          fi
