name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Use Node 18 + npm 9
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3. Verify npm version
      - run: npm --version

      # 4. Install dependencies (from package-lock.json)
      - name: Install dependencies
        run: npm ci

      # 5. Type check + lint
      - name: Verify code quality
        run: |
          npx tsc --noEmit
          npx eslint . --ext .ts,.tsx

      # 6. Run tests (if you add Jest or Detox later)
      - name: Run tests
        run: echo "No tests yet"
